[workspace]
members = [
  "kernel",
  "user-lib",
  "user/init",
  "user/sh",
  "user/ls",
  "user/cat",
  "user/echo",
  "user/grep",
  "user/fork_test",
  "user/pipe_test",
  "user/usertests",
  "user/persist",
  "user/printenv",
  "user/smp_test",
  "user/reclaim_test",
  "user/stress",
  "user/udpping",
  "user/webserver",
  "user/crashwrite",
  "user/ping",
  "tools/mkfs",
  "host-tests",
]
resolver = "2"
